<?php

return [
    'HEADER1' => [
        'BANCO' => [
            'length' => 3,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => 'bbbb',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => 'c',
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_12' => [
            'length' => 9,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'INSCRICAO_TIPO' => [
            'length' => 1,
            'default' => 1,
            'field_id' => null,
            'type' => 'int',
        ],
        'CPF_FONTE_PAG' => [
            'length' => 14,
            'default' => 32159551805,
            'field_id' => null,
            'type' => 'int',
        ],
        'CONVENIO' => [
            'length' => 20,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'AGENCIA' => [
            'length' => 5,
            'default' => '0927',
            'field_id' => null,
            'type' => 'int',
        ],
        'AGENCIA_DIGITO' => [
            'length' => 1,
            'default' => '3',
            'field_id' => null,
            'type' => 'string',
        ],
        'CONTA' => [
            'length' => 12,
            'default' => '0073015',
            'field_id' => null,
            'type' => 'int',
        ],
        'CONTA_DIGITO' => [
            'length' => 1,
            'default' => '7',
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_20' => [
            'length' => 1,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'NOME_EMPRESA' => [
            'length' => 30,
            'default' => 'Elza e Pedro Henrique Entregas Expressas ME',
            'field_id' => null,
            'type' => 'string',
        ],
        'NOME_BANCO' => [
            'length' => 30,
            'default' => 'Banco do Brasil',
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_23' => [
            'length' => 10,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'CODIGO_REMESSA' => [
            'length' => 1,
            'default' => '1',
            'field_id' => null,
            'type' => 'int',
        ],
        'DATA_GER_ARQUIVO' => [
            'length' => 8,
            'default' => '11102020',
            'field_id' => null,
            'type' => 'int',
        ],
        'HORA_GER_ARQUIVO' => [
            'length' => 6,
            'default' => '131233',
            'field_id' => null,
            'type' => 'int',
        ],
        'NUM_SERQUNCIAL_ARQUIVO' => [
            'length' => 6,
            'default' => '000001',
            'field_id' => null,
            'type' => 'int',
        ],
        'LAYOUT_ARQUIVO' => [
            'length' => 3,
            'default' => '030',
            'field_id' => null,
            'type' => 'int',
        ],
        'DENCIDADE_GER_ARQUIVO' => [
            'length' => 5,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_30' => [
            'length' => 54,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_31' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
    ],
    'HEADER2' => [
        'BANCO' => [
            'length' => 3,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => '0001',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => '1',
            'field_id' => null,
            'type' => 'int',
        ],
        'OPERACAO' => [
            'length' => 1,
            'default' => 'C',
            'field_id' => null,
            'type' => 'string',
        ],
        'SERVICO' => [
            'length' => 2,
            'default' => 98,
            'field_id' => null,
            'type' => 'int',
        ],
        'FORMA_LANCAMENTO' => [
            'length' => 2,
            'default' => 03,
            'field_id' => null,
            'type' => 'int',
        ],
        'LAYOUT_LOTE' => [
            'length' => 3,
            'default' => '020',
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_43' => [
            'length' => 1,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'INSCRICAO_TIPO' => [
            'length' => 1,
            'default' => '25256',
            'field_id' => null,
            'type' => 'int',
        ],
        'INSCRICAO_NUMERO' => [
            'length' => 14,
            'default' => '25256',
            'field_id' => null,
            'type' => 'int',
        ],
        'CONVENIO' => [
            'length' => 20,
            'default' => '25256',
            'field_id' => null,
            'type' => 'string',
        ],
        'AGENCIA' => [
            'length' => 5,
            'default' => '25256',
            'field_id' => null,
            'type' => 'int',
        ],
        'AGENCIA_DIGITO' => [
            'length' => 1,
            'default' => '1',
            'field_id' => null,
            'type' => 'string',
        ],
        'CONTA' => [
            'length' => 12,
            'default' => '1651',
            'field_id' => null,
            'type' => 'int',
        ],
        'CONTA_DIGITO' => [
            'length' => 1,
            'default' => '1651',
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_51' => [
            'length' => 1,
            'default' => '1651',
            'field_id' => null,
            'type' => 'int',
        ],
        'NOME_EMPRESA' => [
            'length' => 30,
            'default' => 'Elza e Pedro Henrique Entregas Expressas ME',
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_40' => [
            'length' => 40,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'LOGRADOURO' => [
            'length' => 30,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'NUMERO' => [
            'length' => 5,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'COMPLEMENTO' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'CIDADE' => [
            'length' => 20,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'CEP' => [
            'length' => 8,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'ESTADO' => [
            'length' => 2,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_60' => [
            'length' => 8,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_61' => [
            'length' => 10,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
    ],    
    'DETALHE1' => [
        'BANCO' => [
            'length' => 3,
            'default' => '001',
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => '0001',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => '3',
            'field_id' => null,
            'type' => 'int',
        ],
        'NUMERO_REGISTRO' => [
            'length' => 5,
            'default' => '00001',
            'field_id' => null,
            'type' => 'int',
        ],
        'SEGMENTO' => [
            'length' => 1,
            'default' => 'A',
            'field_id' => null,
            'type' => 'string',
        ],
        'TIPO_MOVIMENTO' => [
            'length' => 1,
            'default' => '0',
            'field_id' => null,
            'type' => 'int',
        ],
        'CODIGO_MOVIMENTO' => [
            'length' => 2,
            'default' => '00',
            'field_id' => null,
            'type' => 'int',
        ],       
        'CAMARA_CENTRALIZADORA' => [
            'length' => 3,
            'default' => '033',
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_CODIGO_BANCO' => [
            'length' => 3,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_AGENCIA' => [
            'length' => 5,
            'default' => null,
            'field_id' => 'field_3',
            'type' => 'int',
        ],
        'BEN_AGENCIA_DIGITO' => [
            'length' => 1,
            'default' => null,
            'field_id' => 'field_3',
            'type' => 'string',
        ],
        'BEN_CONTA' => [
            'length' => 12,
            'default' => null,
            'field_id' => 'field_7',
            'type' => 'int',
        ],
        'BEN_CONTA_DIGITO' => [
            'length' => 1,
            'default' => null,
            'field_id' => 'field_7',
            'type' => 'string',
        ],
        'BEN_DIGITO_CONTA_AGENCIA_80' => [
            'length' => 1,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'BEN_NOME' => [
            'length' => 30,
            'default' => null,
            'field_id' => 'field_25',
            'type' => 'string',
        ],
        'BEN_DOC_ATRIB_EMPRESA_82' => [
            'length' => 20,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'DATA_PAGAMENTO' => [
            'length' => 8,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'TIPO_MOEDA' => [
            'length' => 3,
            'default' => 'BRL',
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_85' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'VALOR_INTEIRO' => [
            'length' => 13,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'VALOR_DECIMAL' => [
            'length' => 2,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'VALOR_DECIMAL' => [
            'length' => 2,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_88' => [
            'length' => 20,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_89' => [
            'length' => 23,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_90' => [
            'length' => 42,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'CODIGO_FINALIDADE_TED' => [
            'length' => 5,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_92' => [
            'length' => 5,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_93' => [
            'length' => 11,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        

    ],
    'DETALHE2' => [
        'BANCO' => [
            'length' => 3,
            'default' => '001',
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => '0001',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => '3',
            'field_id' => null,
            'type' => 'int',
        ],
        'NUMERO_REGISTRO' => [
            'length' => 5,
            'default' => '00001',
            'field_id' => null,
            'type' => 'int',
        ],
        'SEGMENTO' => [
            'length' => 1,
            'default' => 'B',
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_104' => [
            'length' => 3,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'BEN_TIPO_DOC' => [
            'length' => 1,
            'default' => 1,
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_CPF' => [
            'length' => 14,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_ENDERECO_LOGRADOURO' => [
            'length' => 30,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'BEN_ENDERECO_NUMERO' => [
            'length' => 5,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_ENDERECO_COMPLEMENTO' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],        
        'BEN_ENDERECO_BAIRRO' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],        
        'BEN_ENDERECO_CIDADE' => [
            'length' => 20,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'BEN_ENDERECO_CEP' => [
            'length' => 8,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'BEN_ENDERECO_ESTADO' => [
            'length' => 2,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_114' => [
            'length' => 83,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_115' => [
            'length' => 15,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_116' => [
            'length' => 7,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_117' => [
            'length' => 8,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
    ],
    'TRAILER1' => [
        'BANCO' => [
            'length' => 3,
            'default' => '001',
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => '0001',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => '5',
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_126' => [
            'length' => 9,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'QUANTIDADE_REGISTROS_127' => [
            'length' => 6,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'VALOR_TOTAL_DOC_INTEIRO' => [
            'length' => 16,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'VALOR_TOTAL_DOC_DECIMAL' => [
            'length' => 2,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_130' => [
            'length' => 24,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_131' => [
            'length' => 165,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'USO_BANCO_132' => [
            'length' => 10,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
    ],
    'TRAILER2' => [
        'BANCO' => [
            'length' => 3,
            'default' => '001',
            'field_id' => null,
            'type' => 'int',
        ],
        'LOTE' => [
            'length' => 4,
            'default' => '0001',
            'field_id' => null,
            'type' => 'int',
        ],
        'REGISTRO' => [
            'length' => 1,
            'default' => '5',
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_141' => [
            'length' => 9,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ],
        'QUANTIDADE_LOTES-ARQUIVO' => [
            'length' => 6,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'QUANTIDADE_REGISTROS_ARQUIVOS' => [
            'length' => 6,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],       
        'USO_BANCO_144' => [
            'length' => 6,
            'default' => null,
            'field_id' => null,
            'type' => 'int',
        ],
        'USO_BANCO_145' => [
            'length' => 205,
            'default' => null,
            'field_id' => null,
            'type' => 'string',
        ]       
    ],
    "parameters_default" => [
        "status" => 10,
    ],
];
