<?php
return [
    "fields_cpf" => [ // Campos para CPF
        'CPF' => '',
        'SEXO' => '',
        'NOME_ESPACO_CULTURAL' => [],
        'FLAG_CAD_ESTADUAL' => '',
        'SISTEMA_CAD_ESTADUAL' => '',
        'IDENTIFICADOR_CAD_ESTADUAL' => '',
        'FLAG_CAD_MUNICIPAL' => '',
        'SISTEMA_CAD_MUNICIPAL' => '',
        'IDENTIFICADOR_CAD_MUNICIPAL' => '',
        'FLAG_CAD_DISTRITAL' => '',
        'SISTEMA_CAD_DISTRITAL' => '',
        'IDENTIFICADOR_CAD_DISTRITAL' => '',
        'FLAG_CAD_NA_PONTOS_PONTOES' => '',
        'FLAG_CAD_ES_PONTOS_PONTOES' => '',
        'SISTEMA_CAD_ES_PONTOS_PONTOES' => '',
        'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES' => '',
        'FLAG_CAD_SNIIC' => '',
        'SISTEMA_CAD_SNIIC' => '',
        'IDENTIFICADOR_CAD_SNIIC' => '',
        'FLAG_CAD_SALIC' => '',
        'FLAG_CAD_SICAB' => '',
        'FLAG_CAD_OUTROS' => '',
        'SISTEMA_CAD_OUTROS' => '',
        'IDENTIFICADOR_CAD_OUTROS' => '',
        'FLAG_ATUACAO_ARTES_CENICAS' => [],
        'FLAG_ATUACAO_AUDIOVISUAL' => [],
        'FLAG_ATUACAO_MUSICA' => [],
        'FLAG_ATUACAO_ARTES_VISUAIS' => [],
        'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => [],
        'FLAG_ATUACAO_MUSEUS_MEMORIA' => [],
        'FLAG_ATUACAO_HUMANIDADES' => [],
    ],
    "fields_cnpj" => [ // Campos para CNPJ
        'CNPJ' => [],
        'FLAG_CAD_ESTADUAL' => '',
        'SISTEMA_CAD_ESTADUAL' => '',
        'IDENTIFICADOR_CAD_ESTADUAL' => '',
        'FLAG_CAD_MUNICIPAL' => '',
        'SISTEMA_CAD_MUNICIPAL' => '',
        'IDENTIFICADOR_CAD_MUNICIPAL' => '',
        'FLAG_CAD_DISTRITAL' => '',
        'SISTEMA_CAD_DISTRITAL' => '',
        'IDENTIFICADOR_CAD_DISTRITAL' => '',
        'FLAG_CAD_NA_PONTOS_PONTOES' => '',
        'FLAG_CAD_ES_PONTOS_PONTOES' => '',
        'SISTEMA_CAD_ES_PONTOS_PONTOES' => '',
        'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES' => '',
        'FLAG_CAD_SNIIC' => '',
        'SISTEMA_CAD_SNIIC' => '',
        'IDENTIFICADOR_CAD_SNIIC' => '',
        'FLAG_CAD_SALIC' => '',
        'FLAG_CAD_SICAB' => '',
        'FLAG_CAD_OUTROS' => '',
        'SISTEMA_CAD_OUTROS' => '',
        'IDENTIFICADOR_CAD_OUTROS' => '',
        'FLAG_ATUACAO_ARTES_CENICAS' => [],
        'FLAG_ATUACAO_AUDIOVISUAL' => [],
        'FLAG_ATUACAO_MUSICA' => [],
        'FLAG_ATUACAO_ARTES_VISUAIS' => [],
        'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => [],
        'FLAG_ATUACAO_MUSEUS_MEMORIA' => [],
        'FLAG_ATUACAO_HUMANIDADES' => [],
    ],
    "inscricoes_culturais" => [ // Opções para incrições culturais
        'mapa-cultural' => '',
        'cadastro-municipal' => '',
        'sniic' => '',
        'salic' => '',
        'sicab' => '',
        'outros' => '',
    ],
    "category" => [ // Categorias
        'com_espaco_fisico' => [],
        'sem_espaco_fisico' => [],

    ],
    'atuacoes-culturais' => [ // Opções para área de atuações culturais
        'artes-cenicas' => [
            'Artes Circenses',
            'Dança',
            'Teatro',
            'Ópera',
        ],
        'artes-visuais' => [
            'Artes Visuais',
            'Artesanato',
            'Design',
            'Fotografia',
            'Moda',
        ],
        'audiovisual' => [
            'Audiovisual',
        ],
        'humanidades' => [
            'Literatura',
        ],
        'museu-memoria' => [
            'Museu',
        ],
        'musica' => [
            'Música',
        ],
        'patrimonio-cultural' => [
            'Cultura Popular',
            'Gastronomia',
            'Outros',
            'Patrimônio Cultural',
        ],

    ],
];
