<?php

return [
    'header' =>[       
        'CPF',
        'NOME_SOCIAL', 
        'CNPJ',
        'RAZAO_SOCIAL',             
        'LOGRADOURO',
        'NUMERO',
        'COMPLEMENTO',
        'BAIRRO',
        'MUNICIPIO',
        'CEP',
        'ESTADO',
        'TELEFONE',
        'NUM_BANCO',
        //'TIPO_CONTA_BANCO',        
        'AGENCIA_BANCO',
        'CONTA_BANCO',
        //'OPERACAO_BANCO',
        'VALOR',
        'INSCRICAO_ID',
        'INCISO',
    ],
    '4788' => [ 
        'TIPO_PROPONENTE' => 'field_1098',        
        'CPF' => 'field_1104',
        'NOME_SOCIAL' => 'field_1094',    
        'CNPJ' => 'field_1118',
        'RAZAO_SOCIAL' => 'field_1117',                
        'LOGRADOURO' => 'field_1121',
        'NUMERO' => 'field_1121',
        'COMPLEMENTO' => 'field_1121',
        'BAIRRO' => 'field_1121',
        'MUNICIPIO' => 'field_1121',
        'CEP' => 'field_1121',
        'ESTADO' => 'field_1121',
        'TELEFONE' => 'field_1105',
        'NUM_BANCO' => 'field_1122' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1099',
        'CONTA_BANCO'  => 'field_1113',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4789' => [ 
        'TIPO_PROPONENTE' => null,        
        'CPF' => 'field_1126',
        'NOME_SOCIAL' => 'field_1143',    
        'CNPJ' => null,
        'RAZAO_SOCIAL' => null,                
        'LOGRADOURO' => 'field_1150',
        'NUMERO' => 'field_1150',
        'COMPLEMENTO' => 'field_1150',
        'BAIRRO' => 'field_1150',
        'MUNICIPIO' => 'field_1150',
        'CEP' => 'field_1150',
        'ESTADO' => 'field_1150',
        'TELEFONE' => 'field_1142',
        'NUM_BANCO' => 'field_1127' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1128',
        'CONTA_BANCO'  => 'field_1152',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4790' => [ 
        'TIPO_PROPONENTE' => null,        
        'CPF' => 'field_1169',
        'NOME_SOCIAL' => 'field_1161',    
        'CNPJ' => null,
        'RAZAO_SOCIAL' => null,                
        'LOGRADOURO' => 'field_1156',
        'NUMERO' => 'field_1156',
        'COMPLEMENTO' => 'field_1156',
        'BAIRRO' => 'field_1156',
        'MUNICIPIO' => 'field_1156',
        'CEP' => 'field_1156',
        'ESTADO' => 'field_1156',
        'TELEFONE' => 'field_1159',
        'NUM_BANCO' => 'field_1171' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1162',
        'CONTA_BANCO'  => 'field_1163',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4791' => [ 
        'TIPO_PROPONENTE' => 'field_1302',        
        'CPF' => 'field_1188',
        'NOME_SOCIAL' => 'field_1175',    
        'CNPJ' => 'field_1310',
        'RAZAO_SOCIAL' => 'field_1303',                
        'LOGRADOURO' => 'field_1184',
        'NUMERO' => 'field_1184',
        'COMPLEMENTO' => 'field_1184',
        'BAIRRO' => 'field_1184',
        'MUNICIPIO' => 'field_1184',
        'CEP' => 'field_1184',
        'ESTADO' => 'field_1184',
        'TELEFONE' => 'field_1187',
        'NUM_BANCO' => 'field_1190' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1176',
        'CONTA_BANCO'  => 'field_1177',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4792' => [ 
        'TIPO_PROPONENTE' => null,        
        'CPF' => 'field_1199',
        'NOME_SOCIAL' => 'field_1201',    
        'CNPJ' => null,
        'RAZAO_SOCIAL' => null,                
        'LOGRADOURO' => 'field_1195',
        'NUMERO' => 'field_1195',
        'COMPLEMENTO' => 'field_1195',
        'BAIRRO' => 'field_1195',
        'MUNICIPIO' => 'field_1195',
        'CEP' => 'field_1195',
        'ESTADO' => 'field_1195',
        'TELEFONE' => 'field_1112',
        'NUM_BANCO' => 'field_1202' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1203',
        'CONTA_BANCO'  => 'field_1204',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4793' => [ 
        'TIPO_PROPONENTE' => 'field_1215',        
        'CPF' => 'field_1238',
        'NOME_SOCIAL' => 'field_1221',    
        'CNPJ' => null,
        'RAZAO_SOCIAL' => null,                
        'LOGRADOURO' => 'field_1214',
        'NUMERO' => 'field_1214',
        'COMPLEMENTO' => 'field_1214',
        'BAIRRO' => 'field_1214',
        'MUNICIPIO' => 'field_1214',
        'CEP' => 'field_1214',
        'ESTADO' => 'field_1214',
        'TELEFONE' => 'field_1226',
        'NUM_BANCO' => 'field_1236' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1233',
        'CONTA_BANCO'  => 'field_1234',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4794' => [ 
        'TIPO_PROPONENTE' => null,        
        'CPF' => 'field_1251',
        'NOME_SOCIAL' => 'field_1250',    
        'CNPJ' => 'field_1242',
        'RAZAO_SOCIAL' => 'field_1304',                
        'LOGRADOURO' => 'field_1247',
        'NUMERO' => null,
        'COMPLEMENTO' => null,
        'BAIRRO' => null,
        'MUNICIPIO' => null,
        'CEP' => 'field_1249',
        'ESTADO' => null,
        'TELEFONE' => 'field_1256',
        'NUM_BANCO' => 'field_1255' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1301',
        'CONTA_BANCO'  => 'field_1262',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    '4795' => [ 
        'TIPO_PROPONENTE' => 'field_1294',        
        'CPF' => 'field_1291',
        'NOME_SOCIAL' => 'field_1293',    
        'CNPJ' => 'field_1279',
        'RAZAO_SOCIAL' => 'field_1304',                
        'LOGRADOURO' => 'field_1277',
        'NUMERO' => null,
        'COMPLEMENTO' => null,
        'BAIRRO' => null,
        'MUNICIPIO' => null,
        'CEP' => 'field_1276',
        'ESTADO' => null,
        'TELEFONE' => 'field_1292',
        'NUM_BANCO' => 'field_1284' ,
        'TIPO_CONTA_BANCO' => 0,        
        'AGENCIA_BANCO' => 'field_1296',
        'CONTA_BANCO'  => 'field_1298',
        'OPERACAO_BANCO'  => '',
        'VALOR' => '600',        
        'INCISO' => 1291,
    ],
    
    
    
    
    'parameters_default' => [
        'status' => '10',
        'searchType' => 'field_id',
        'proponentTypes' => [
            'fisica' => 'Pessoa Física',
            'juridica' => 'Pessoa Jurídica',
            'coletivo' => 'Coletivo'
        ]
    ],
    
        

];