<?php
return[
   "fields_cpf" => [ 
      'CPF' => 'CPF DO RESPONSÁVEL PELO ESPAÇO CULTURAL, EMPRESA, ENTIDADE OU COOPERATIVA CULTURAL:',
      'SEXO' => 'SEXO DO RESPONSÁVEL PELO ESPAÇO CULTURAL, EMPRESA, ENTIDADE OU COOPERATIVA CULTURAL:',
      'NOME_ESPACO_CULTURAL' => [
         'NOME DO COLETIVO',
         'NOME DO ESPAÇO CULTURAL VINCULADO OU MANTIDO PELO BENEFICIÁRIO DO SUBSÍDIO:'
      ],
      'FLAG_CAD_ESTADUAL' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_ESTADUAL' => null,
      'IDENTIFICADOR_CAD_ESTADUAL' => null,
      'FLAG_CAD_MUNICIPAL' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_MUNICIPAL' => null,
      'IDENTIFICADOR_CAD_MUNICIPAL' => null,
      'FLAG_CAD_DISTRITAL' => 'dados vem da config',
      'SISTEMA_CAD_DISTRITAL' => 'dados vem da config',
      'IDENTIFICADOR_CAD_DISTRITAL' => 'dados vem da config',
      'FLAG_CAD_NA_PONTOS_PONTOES' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_ES_PONTOS_PONTOES' => 'dados vem da config',
      'SISTEMA_CAD_ES_PONTOS_PONTOES' => 'caso FLAG_CAD_ES_PONTOS_PONTOES = 1 pega dados da config',
      'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES' => 'caso FLAG_CAD_ES_PONTOS_PONTOES = 1 pega dados da config',
      'FLAG_CAD_SNIIC' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_SNIIC' => 'caso FLAG_CAD_SNIIC = 1 pega dados da config',
      'IDENTIFICADOR_CAD_SNIIC' => 'caso FLAG_CAD_SNIIC = 1 pega dados da config',
      'FLAG_CAD_SALIC' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_SICAB' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_OUTROS' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_OUTROS' => 'Outros',
      'IDENTIFICADOR_CAD_OUTROS' => 'Outros',
      'FLAG_ATUACAO_ARTES_CENICAS' => 'category',
      'FLAG_ATUACAO_AUDIOVISUAL' => 'category',
      'FLAG_ATUACAO_MUSICA' => 'category',
      'FLAG_ATUACAO_ARTES_VISUAIS' => 'category',
      'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 'category',
      'FLAG_ATUACAO_MUSEUS_MEMORIA' => 'category',
      'FLAG_ATUACAO_HUMANIDADES' => 'category',
],
   "fields_cnpj" => [
      'CNPJ' => [
         'NÚMERO DE INSCRIÇÃO EM CADASTRO NACIONAL DE PESSOA JURÍDICA – CNPJ:', 
         'NÚMERO DE INSCRIÇÃO EM CADASTRO NACIONAL DE PESSOA JURÍDICA – CNPJ:'
      ],
      'FLAG_CAD_ESTADUAL' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_ESTADUAL' => null,
      'IDENTIFICADOR_CAD_ESTADUAL' => null,
      'FLAG_CAD_MUNICIPAL' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_MUNICIPAL' => null,
      'IDENTIFICADOR_CAD_MUNICIPAL' => null,
      'FLAG_CAD_DISTRITAL' => 'dados vem da config',
      'SISTEMA_CAD_DISTRITAL' => 'dados vem da config',
      'IDENTIFICADOR_CAD_DISTRITAL' => 'dados vem da config',
      'FLAG_CAD_NA_PONTOS_PONTOES' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_ES_PONTOS_PONTOES' => 'dados vem da config',
      'SISTEMA_CAD_ES_PONTOS_PONTOES' => 'caso FLAG_CAD_ES_PONTOS_PONTOES = 1 pega dados da config',
      'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES' => 'caso FLAG_CAD_ES_PONTOS_PONTOES = 1 pega dados da config',
      'FLAG_CAD_SNIIC' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_SNIIC' => 'caso FLAG_CAD_SNIIC = 1 pega dados da config',
      'IDENTIFICADOR_CAD_SNIIC' => 'caso FLAG_CAD_SNIIC = 1 pega dados da config',
      'FLAG_CAD_SALIC' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_SICAB' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'FLAG_CAD_OUTROS' => 'INSCRIÇÃO EM CADASTRO CULTURAL:',
      'SISTEMA_CAD_OUTROS' => 'dados vem da config',
      'IDENTIFICADOR_CAD_OUTROS' => 'dados vem da config',
      'FLAG_ATUACAO_ARTES_CENICAS' => 'category',
      'FLAG_ATUACAO_AUDIOVISUAL' => 'category',
      'FLAG_ATUACAO_MUSICA' => 'category',
      'FLAG_ATUACAO_ARTES_VISUAIS' => 'category',
      'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 'category',
      'FLAG_ATUACAO_MUSEUS_MEMORIA' => 'category',
      'FLAG_ATUACAO_HUMANIDADES' => 'category',
   ],
   "category" => [
      'COM_ESPAÇO_FISICO' => 'field_406',
      'SEM_ESPAÇO_FISICO' => 'field_379'
   ]
];